# Generated by Django 5.0.6 on 2024-05-26 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_authors_type_of_painting_iatp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
